// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsXY8kgkRJ0_YOxS7nxltDbc45Ty-P1NQ',
    appId: '1:467777538875:web:ff5c7ed983c0542732451e',
    messagingSenderId: '467777538875',
    projectId: 'student-9098c',
    authDomain: 'student-9098c.firebaseapp.com',
    storageBucket: 'student-9098c.appspot.com',
    measurementId: 'G-S0NLPH2267',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0Hmi8v2IwbnvziKB0Z213CQXhft8-QJg',
    appId: '1:467777538875:android:ca2571de323c223f32451e',
    messagingSenderId: '467777538875',
    projectId: 'student-9098c',
    storageBucket: 'student-9098c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLWXEx-asIxLfYIJzS62CLFEB7Tyi0VVA',
    appId: '1:467777538875:ios:99e399bfc1b2f6b532451e',
    messagingSenderId: '467777538875',
    projectId: 'student-9098c',
    storageBucket: 'student-9098c.appspot.com',
    iosBundleId: 'com.example.student',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLWXEx-asIxLfYIJzS62CLFEB7Tyi0VVA',
    appId: '1:467777538875:ios:99e399bfc1b2f6b532451e',
    messagingSenderId: '467777538875',
    projectId: 'student-9098c',
    storageBucket: 'student-9098c.appspot.com',
    iosBundleId: 'com.example.student',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsXY8kgkRJ0_YOxS7nxltDbc45Ty-P1NQ',
    appId: '1:467777538875:web:cdca876e8cebdfd832451e',
    messagingSenderId: '467777538875',
    projectId: 'student-9098c',
    authDomain: 'student-9098c.firebaseapp.com',
    storageBucket: 'student-9098c.appspot.com',
    measurementId: 'G-QYVEL4L6QT',
  );
}
